<?php


namespace fredbradley\CranleighGoogleApi\Resources;


use Illuminate\Http\Resources\Json\JsonResource;

class GoogleActivityResource extends JsonResource
{
    public function toArray($request)
    {
        dd($request);
        return [
            'id' => $this->etag
        ];
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
